name: Webhook action 
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    # - uses: actions/checkout@master
    - name: send auth token
      uses: obbap1/webhook-action@master
      env:
        AUTH_TOKEN: ''
      with:
        routeToTest: ${{JSON.stringify([{route:"/", method:"GET"}])}}
        baseURL: http://cdf4d406.ngrok.io
        hook: /web-hook  