name: Webhook action 
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: send auth token
      uses: obbap1/webhook-action@master 
      uses: actions/checkout@master
      env:
        AUTH_TOKEN: ''
      with:
        routeToTest: ${{ secrets.ARRAY_OF_VALUES  }}
        baseURL: http://cdf4d406.ngrok.io
        hook: /web-hook  